# Generated by Django 5.1.1 on 2024-10-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battel_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_default_health', models.IntegerField(default=15)),
                ('Player_current_health', models.IntegerField(default=15)),
                ('Enemy_default_health', models.IntegerField(default=15)),
                ('Enemy_current_health', models.IntegerField(default=15)),
                ('Enemy_skill1_cooldown', models.IntegerField(default=0)),
                ('Enemy_skill2_cooldown', models.IntegerField(default=0)),
                ('Player_item1_cooldown', models.IntegerField(default=0)),
                ('Player_item2_cooldown', models.IntegerField(default=0)),
                ('Player_item3_cooldown', models.IntegerField(default=0)),
                ('Player_item4_cooldown', models.IntegerField(default=0)),
                ('Player_item5_cooldown', models.IntegerField(default=0)),
                ('Player_item6_cooldown', models.IntegerField(default=0)),
                ('Enemy_battel_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.IntegerField(default=1)),
                ('item1', models.IntegerField(default=0)),
                ('item2', models.IntegerField(default=0)),
                ('item3', models.IntegerField(default=0)),
                ('item4', models.IntegerField(default=0)),
                ('item5', models.IntegerField(default=0)),
                ('item6', models.IntegerField(default=0)),
                ('is_have_heal', models.BooleanField(default=False)),
                ('is_have_empty_slot', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('enemy_class', models.IntegerField(default=1)),
                ('enemy_description', models.TextField(blank=True, null=True)),
                ('health', models.IntegerField(default=5)),
                ('enemy_skill1_id', models.IntegerField(default=0)),
                ('enemy_skill2_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
                ('skill_id', models.IntegerField(default=1)),
                ('skill_type', models.CharField(default='Attack', max_length=30)),
                ('skill_description', models.TextField(blank=True, null=True)),
                ('skill_effect_max', models.IntegerField(default=3)),
                ('skill_effect_min', models.IntegerField(default=1)),
                ('skill_cooldown', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('item_type', models.CharField(default='Empty', max_length=30)),
                ('item_name', models.CharField(default='Empty', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('skill_description', models.CharField(max_length=30, null=True)),
                ('skill_effect_max', models.IntegerField(default=3)),
                ('skill_effect_min', models.IntegerField(default=1)),
                ('skill_cooldown', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item_tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(null=True)),
                ('location_name', models.CharField(max_length=30)),
                ('location_type', models.CharField(default='Empty', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location_trap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Trap', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('trap_found', models.BooleanField(default=False)),
                ('trap_damage_max', models.IntegerField(default=3)),
                ('trap_damage_min', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Location_type_empty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Empty', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location_type_enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Enemy', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('enemy_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location_type_riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Riddle', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('riddle_answer', models.CharField(max_length=30)),
                ('riddle_solved_text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(null=True)),
                ('location_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map_len',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_len', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('player_class', models.IntegerField(default=1)),
                ('player_inventory', models.IntegerField(default=1)),
                ('player_heals', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Player_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(default=1)),
                ('class_heals', models.IntegerField(default=15)),
                ('class_name', models.CharField(max_length=30)),
                ('class_description', models.CharField(default='', max_length=30)),
                ('class_inventory', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.IntegerField(default=1)),
                ('item1', models.IntegerField(default=0)),
                ('item2', models.IntegerField(default=0)),
                ('item3', models.IntegerField(default=0)),
                ('item4', models.IntegerField(default=0)),
                ('item5', models.IntegerField(default=0)),
                ('item6', models.IntegerField(default=0)),
                ('is_have_heal', models.BooleanField(default=False)),
                ('is_have_empty_slot', models.BooleanField(default=True)),
            ],
        ),
    ]
