# Generated by Django 5.1.1 on 2024-10-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_heals',
            new_name='player_health',
        ),
    ]
