# Generated by Django 5.1.1 on 2024-10-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quest', '0002_rename_player_heals_player_player_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_trap',
            name='trap_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
