# Generated by Django 5.1.1 on 2024-10-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quest', '0003_location_trap_trap_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='battel_stat',
            name='Enemy_use_skill',
            field=models.CharField(default='Trap', max_length=30),
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Player_use_skill',
            field=models.CharField(default='Trap', max_length=30),
        ),
    ]
