# Generated by Django 5.1.1 on 2024-10-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quest', '0005_remove_battel_stat_enemy_use_skill_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item_tool',
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Is_player_item1_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Is_player_item2_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Is_player_item3_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Is_player_item4_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Is_player_item5_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Is_player_item6_ready',
            field=models.BooleanField(default=True),
        ),
    ]
