# Generated by Django 5.1.1 on 2024-10-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quest', '0006_delete_item_tool_battel_stat_is_player_item1_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_it_tech',
            field=models.BooleanField(default=False),
        ),
    ]
