# Generated by Django 5.1.1 on 2024-10-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quest', '0009_rename_is_player_item1_ready_battel_stat_is_slot1_empty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battel_stat',
            name='Player_item1_default_cooldown',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Player_item2_default_cooldown',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Player_item3_default_cooldown',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Player_item4_default_cooldown',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Player_item5_default_cooldown',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='battel_stat',
            name='Player_item6_default_cooldown',
            field=models.IntegerField(default=99),
        ),
    ]
