# Generated by Django 5.1.1 on 2024-10-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quest', '0011_rename_location_type_empty_location_empty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_trap',
            name='trap_activation_chance',
            field=models.IntegerField(default=36),
        ),
    ]
