# Generated by Django 5.1.1 on 2024-10-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quest', '0012_location_trap_trap_activation_chance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_class',
            old_name='class_heals',
            new_name='class_health',
        ),
    ]
